<a href="https://colab.research.google.com/github/codefromjames/eire.energy/blob/main/geocoding.ppr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install geopandas

Collecting geopandas
  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 8.2 MB/s
Collecting pyproj>=2.2.0
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 13.6 MB/s
Collecting fiona>=1.8
  Downloading Fiona-1.8.20-cp37-cp37m-manylinux1_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 24.0 MB/s
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.0)
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.10.8)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.4.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.19.5)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.20 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
import io

In [3]:
uploaded = files.upload()
ppr = pd.read_csv(io.BytesIO(uploaded['ppr.not.csv']), encoding= 'unicode_escape')

Saving ppr.not.csv to ppr.not.csv

In [4]:
ppr

      Date of Sale (dd/mm/yyyy)  ... small.area.3
0                    14/01/2010  ...   A017022004
1                    23/04/2010  ...          NaN
2                    14/05/2010  ...          NaN
3                    16/07/2010  ...          NaN
4                    30/07/2010  ...          NaN
...                         ...  ...          ...
65530                31/08/2012  ...          NaN
65531                10/09/2012  ...          NaN
65532                13/09/2012  ...          NaN
65533                18/09/2012  ...          NaN
65534                20/09/2012  ...          NaN

[65535 rows x 15 columns]

Warning: total number of rows (65535) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
ppr

In [ ]:
from geopandas.tools import geocode
from google.colab import files

import time

for index, row in ppr.iterrows():
  try: 
      time.sleep(1)    
      print(row['AddressCO'])
      info = geocode(str(row['AddressCO']), provider = 'nominatim', user_agent = 'my_request' )
      ppr.loc[int(index), 'found'] = info['address'].loc[0]
      ppr.loc[int(index), 'Lon'] = info['geometry'].loc[0].x
      ppr.loc[int(index), 'Lat'] = info['geometry'].loc[0].y
      print(row['index'])
  except Exception as e:
      ppr.loc[int(index), 'found'] =  "No Result"


ppr.to_csv('ppr.geo.csv') 
files.download('ppr.geo.csv')